name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/cli@main

      - name: Install Geode SDK
        run: |
          geode sdk install v5.10.1
          geode sdk install-binaries

      - name: Build Mod
        run: |
          mkdir -p build
          geode build

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/*.geode
