name: Build Rainbow Icon

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android64:
    name: Build Android64 .geode
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          build-config: Release
          use-lto: true

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: RainbowIcon-Android64
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
